# Generated by Django 3.0.4 on 2020-03-10 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('time_to_obtain_visa', models.IntegerField(null=True)),
                ('advance_days_required', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('passport_no', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('residence_country', models.CharField(max_length=30)),
                ('residence_city', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=30, null=True)),
                ('cost_per_night', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_planner_app.City')),
            ],
        ),
        migrations.CreateModel(
            name='TravelBookingSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_comment', models.TextField(null=True)),
                ('supervisor_comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_on', models.DateField()),
                ('validity_days', models.IntegerField()),
                ('extension_option', models.NullBooleanField(default=False)),
                ('visa_cost', models.FloatField(default=0)),
                ('travel_booking_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_planner_app.TravelBookingSummary')),
            ],
        ),
        migrations.CreateModel(
            name='TravelCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date_start', models.DateField()),
                ('travel_date_end', models.DateField()),
                ('city_destination', models.CharField(max_length=64)),
                ('country_destination', models.DateField()),
                ('travel_purpose_description', models.TextField(null=True)),
                ('employee_approval', models.NullBooleanField(default=True)),
                ('supervisor_approval', models.NullBooleanField(default=False)),
                ('notification_advance', models.IntegerField(default=14)),
                ('city_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_planner_app.City')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_planner_app.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='travelbookingsummary',
            name='travel_calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_planner_app.TravelCalendar'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date_start', models.DateField()),
                ('travel_date_end', models.DateField()),
                ('airport_departure', models.CharField(max_length=64)),
                ('airport_arrival', models.CharField(max_length=64)),
                ('ticket_cost', models.FloatField()),
                ('supervisor_approval', models.BooleanField(default=False)),
                ('travel_booking_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_planner_app.TravelBookingSummary')),
            ],
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('cost_per_stay', models.FloatField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_planner_app.Hotel')),
                ('travel_booking_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_planner_app.TravelBookingSummary')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_planner_app.Country'),
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('IATA_code', models.CharField(max_length=6)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_planner_app.City')),
            ],
        ),
    ]
