# Generated by Django 3.0.4 on 2020-03-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0002_auto_20200310_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelcalendar',
            name='country_destination',
            field=models.CharField(max_length=64),
        ),
    ]
