# Generated by Django 3.0.4 on 2020-03-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0003_auto_20200310_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='airport_arrival',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='airport_departure',
            field=models.CharField(max_length=128),
        ),
    ]
