# Generated by Django 3.0.4 on 2020-03-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0005_auto_20200312_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='cost_per_stay',
        ),
    ]
