# Generated by Django 3.0.4 on 2020-03-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0006_remove_hotelbooking_cost_per_stay'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_validity',
            field=models.DateField(default='2020-02-02'),
            preserve_default=False,
        ),
    ]
