# Generated by Django 3.0.4 on 2020-03-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0007_auto_20200312_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='residence_city',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='employee',
            name='residence_country',
            field=models.CharField(max_length=128),
        ),
    ]
