# Generated by Django 3.0.4 on 2020-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0008_auto_20200312_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_no',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=128),
        ),
    ]
