# Generated by Django 3.0.4 on 2020-05-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0014_travelcostsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravelCostSummary',
        ),
    ]
