# Generated by Django 3.0.4 on 2020-05-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0016_travelcostsummary'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='travelcostsummary',
            table='v_travel_cost_summary2',
        ),
    ]
