# Generated by Django 3.0.4 on 2020-05-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0017_auto_20200513_1920'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='travelcostsummary',
            table='v_travel_cost_summary',
        ),
    ]
